// _ConversionInfo_EOArchive_English.java
// Generated by EnterpriseObjects palette at Thursday, July 21, 2005 9:11:14 AM America/Denver

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _ConversionInfo_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOForm _nsForm0;
    com.webobjects.eointerface.swing.EOFormCell _eoFormCell0, _eoFormCell1, _eoFormCell2;
    com.webobjects.eointerface.swing.EOView _nsBox0, _nsBox1, _nsCustomView0, _nsDatePicker0;

    public _ConversionInfo_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "studyDesciptionID")) != null)) {
            _eoFormCell2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFormCell)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFormCell2");
        } else {
            _eoFormCell2 = (com.webobjects.eointerface.swing.EOFormCell)_registered(new com.webobjects.eointerface.swing.EOFormCell(), "");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "patientIDField")) != null)) {
            _eoFormCell1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFormCell)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFormCell1");
        } else {
            _eoFormCell1 = (com.webobjects.eointerface.swing.EOFormCell)_registered(new com.webobjects.eointerface.swing.EOFormCell(), "");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "patientNameField")) != null)) {
            _eoFormCell0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFormCell)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFormCell0");
        } else {
            _eoFormCell0 = (com.webobjects.eointerface.swing.EOFormCell)_registered(new com.webobjects.eointerface.swing.EOFormCell(), "");
        }

        _nsForm0 = (com.webobjects.eointerface.swing.EOForm)_registered(new com.webobjects.eointerface.swing.EOForm(3, 1, 1, 8), "NSForm1");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "accessoryView")) != null)) {
            _nsCustomView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView0");
        } else {
            _nsCustomView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "datePicker")) != null)) {
            _nsDatePicker0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsDatePicker0");
        } else {
            _nsDatePicker0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View11");
        }
    }

    protected void _awaken() {
        super._awaken();

        if (_replacedObjects.objectForKey("_eoFormCell2") == null) {
            _connect(_owner(), _eoFormCell2, "studyDesciptionID");
        }

        if (_replacedObjects.objectForKey("_eoFormCell1") == null) {
            _connect(_owner(), _eoFormCell1, "patientIDField");
        }

        if (_replacedObjects.objectForKey("_eoFormCell0") == null) {
            _connect(_owner(), _eoFormCell0, "patientNameField");
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_owner(), _nsCustomView0, "accessoryView");
        }

        if (_replacedObjects.objectForKey("_nsDatePicker0") == null) {
            _connect(_owner(), _nsDatePicker0, "datePicker");
        }
    }

    protected void _init() {
        super._init();
        if (!(_nsBox1.getLayout() instanceof EOViewLayout)) { _nsBox1.setLayout(new EOViewLayout()); }
        _nsDatePicker0.setSize(277, 148);
        _nsDatePicker0.setLocation(16, 7);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsDatePicker0, EOViewLayout.MinXMargin | EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox1.add(_nsDatePicker0);
        if (!(_nsBox0.getLayout() instanceof EOViewLayout)) { _nsBox0.setLayout(new EOViewLayout()); }
        _nsBox1.setSize(353, 166);
        _nsBox1.setLocation(2, 15);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsBox1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsBox1);
        _nsBox0.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Study Date and Time", true, "Lucida Grande", 11, Font.PLAIN));

        if (_replacedObjects.objectForKey("_eoFormCell2") == null) {
            _setFontForComponent(_eoFormCell2, "Lucida Grande", 13, Font.PLAIN);
            _eoFormCell2.setTitle("Study Description");
            _eoFormCell2.setTitleWidth(121);
            _eoFormCell2.fieldComponent().setPreferredSize(new Dimension(2, 22));
            _eoFormCell2.titleComponent().setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        }

        if (_replacedObjects.objectForKey("_eoFormCell1") == null) {
            _setFontForComponent(_eoFormCell1, "Lucida Grande", 13, Font.PLAIN);
            _eoFormCell1.setTitle("Patient  ID");
            _eoFormCell1.setTitleWidth(121);
            _eoFormCell1.fieldComponent().setPreferredSize(new Dimension(2, 22));
            _eoFormCell1.titleComponent().setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        }

        if (_replacedObjects.objectForKey("_eoFormCell0") == null) {
            _setFontForComponent(_eoFormCell0, "Lucida Grande", 13, Font.PLAIN);
            _eoFormCell0.setTitle("Patient Name");
            _eoFormCell0.setTitleWidth(121);
            _eoFormCell0.fieldComponent().setPreferredSize(new Dimension(2, 22));
            _eoFormCell0.titleComponent().setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        }

        _eoFormCell0.setSize(0, 0);
        _eoFormCell0.setLocation(-1, 0);
        _nsForm0.add(_eoFormCell0);
        _eoFormCell1.setSize(0, 0);
        _eoFormCell1.setLocation(-1, 0);
        _nsForm0.add(_eoFormCell1);
        _eoFormCell2.setSize(0, 0);
        _eoFormCell2.setLocation(-1, 0);
        _nsForm0.add(_eoFormCell2);
        _setFontForComponent(_nsForm0, "Lucida Grande", 13, Font.PLAIN);

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            if (!(_nsCustomView0.getLayout() instanceof EOViewLayout)) { _nsCustomView0.setLayout(new EOViewLayout()); }
            _nsForm0.setSize(352, 82);
            _nsForm0.setLocation(20, 20);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsForm0, EOViewLayout.MinXMargin | EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsForm0);
            _nsBox0.setSize(357, 183);
            _nsBox0.setLocation(17, 118);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.MinXMargin | EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsBox0);
        }

        if (_replacedObjects.objectForKey("_nsDatePicker0") == null) {
            _setFontForComponent(_nsDatePicker0, "Lucida Grande", 13, Font.PLAIN);
        }
    }
}
